### Search API
POST http://localhost:8080/search/software
Content-Type: application/json

{
    "serial": "Solutions payment deposit",
    "firmware": "",
    "software": "1.1",
    "updateKeys": [

    ]
}
