name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: boardUpdates pipeline
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 14.16.0
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'

            - name: Package application
              run: |
                  chmod +x mvnw
                  ./mvnw -Pprod -ntp package -DskipTests --batch-mode

            - name: Build and publish docker image
              run: |
                  GIT_TAG=:${GITHUB_REF#refs/tags/}
                  ./mvnw -ntp jib:build -Djib.to.image=ghcr.io/dashasan/board-updates:latest -Djib.to.auth.username="${{ github.actor }}" -Djib.to.auth.password="${{ secrets.GITHUB_TOKEN }}"
