name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: boardUpdates pipeline
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            REGISTRY: ghcr.io
            IMAGE_NAME: ${{ github.repository }}
            NODE_VERSION: 14.16.0
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-java@v1
              with:
                  java-version: '11.x'

            - name: Package application
              run: |
                  chmod +x mvnw
                  ./mvnw -Pprod -ntp package -DskipTests --batch-mode

            - name: Docker Login
              uses: docker/login-action@6af3c118c8376c675363897acf1757f7a9be6583
              with:
                username: ${{ github.actor }}
                password: ${{ secrets.TOKEN }}

            - name: Build and publish docker image
              run: ./mvnw -ntp jib:build -Djib.to.image=dashasan/board-updates:latest  -Djib.to.auth.username=${{ github.actor }} -Djib.to.auth.password=${{ secrets.TOKEN }}
